### PR TITLE
PDF Instructions & Makefile

### PR DESCRIPTION
**Pull request by bagnaram**
Adds instructions, requirements, and makefile to generate API PDF with pandoc

### CODE REVIEW

**Comment by bagnaram** [comment]
#66

**Comment by bagnaram** [comment]
any update on this?

**Comment by adityasaky** [comment]
So I see this issue when I run pandoc:

```
Error producing PDF.
! LaTeX Error: Too deeply nested.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.237         \begin{itemize}
```

Are you able to reproduce this? Should we fix something in the markdown file first?

**Comment by adityasaky** [comment]
https://github.com/jgm/pandoc/issues/2922 helped me with a workaround to not using the default nesting in LaTeX.

**Comment by adityasaky** [comment]
@bagnaram WDYT of these changes?

**Pull request merged**
